"""
Thumbnails for courses (modules) and episodes, stored in MongoDB.

Bunny is used for video only, so thumbnails made or uploaded through the
thumbnail studio live here, like notes PDFs. Each image is re-encoded to a
1280x720 WebP at save time (roughly 50-200 KB), well under Mongo's document
limit, and served by id with a long cache: a new image always gets a new id,
so a cached copy can never go stale.

Older thumbnails uploaded to Bunny Storage (thumbnail_bunny_path) keep
working; see services/thumbnails.py for which one wins.
"""
import uuid
from datetime import datetime, timezone
from beanie import Document
from pydantic import Field
from pymongo import IndexModel, ASCENDING

OWNER_MODULE = "module"
OWNER_EPISODE = "episode"
OWNER_KINDS = (OWNER_MODULE, OWNER_EPISODE)

# upload = an image file the admin picked; ai = generated by an image model;
# text = drawn in the browser from a text template (optionally over an image).
SOURCES = ("upload", "ai", "text")


class Thumbnail(Document):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    owner_kind: str  # one of OWNER_KINDS
    owner_id: str
    content_type: str = "image/webp"
    data: bytes
    source: str = "upload"
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Settings:
        name = "thumbnails"
        indexes = [IndexModel([("owner_kind", ASCENDING), ("owner_id", ASCENDING)])]
